import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import './theme.css';
import 'primereact/resources/primereact.min.css';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Oliver Schwab</title>
        <meta property='og:image' content='public\next.svg'></meta>
      </head>
      <body>
        <header>
          <nav className='mt-1'>
            <div id="about-me" className='nav-section'>
              <Link href = "#AboutMe">About me</Link>
            </div>
            <div id="education" className='nav-section'>
              <Link href = "#Education">Education</Link>
            </div>
            <div id="experience" className='nav-section'>
              <Link href="#Experience">Experience</Link>
            </div>
            <div id= "professional-development" className='nav-section'>
              <Link href="#Professional-Development"> Professional Development</Link>
            </div>
            <div id = "projects" className='nav-section'>
            <Link href="#Projects">Projects</Link>
            </div>
            <div id = "skills" className='nav-section'>
            <Link href="#Skills">Skills</Link>
            </div>
          </nav>
        </header>
      </body>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
